name: PoopCraft
description: Poop, now available on PocketMine-MP
author: sn3akrr
version: 1.1.2
api: [5.0.0]
main: sn3akrr\poop\PoopCraft
load: STARTUP

permissions:
 poopcraft.command:
  description: Poop command access
  default: true
 poopcraft.command.sneak:
  description: Sneak poop mode
  default: op
 poopcraft.command.hand:
  description: Poop out item in hand
  default: op
 poopcraft.command.all:
  description: Poop out whole inventory
  default: op
 poopcraft.command.jetpack:
  description: Poop jetpack
  default: op
